version: "3.9"
services:
  applicacion:
    build: .
    ports:
      - "3000:3000"
    links:
      - monguito
  monguito:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      # mysql -> /var/lib/mysql
      # postgresql -> /var/lib/postgresql/data
volumes:
  mongo-data: